time_reset_password: 2
avatar_size: 200
min_tasks_of_subject: 1
status:
  not_start:
    status: "not_start"
    title: "Not start"
    check_box: false
    status_class: "status-not-start"
    label_class: "label-warning label" 
  trainning:
    status: "trainning"
    title: "Trainning"
    check_box: false
    status_class: "status-trainning"
    label_class: "label-success label"
  finish:
    status: "finish"
    title: "Finish"
    check_box: true
    status_class: "status-finish" 
    label_class: "label-default label"
target_type:
  course: 1
  subject: 2
  task: 3
get_user_subjects_query: "user_id = ? and status != 0"  
start: "start"
finish: "finish"
limit_activity: 40
time_format: "%F"
